### ISSUE TITLE
Filling animation is missing/broken

### ISSUE THREAD

**Issue by teleject** [sophshep/isthelakefullyet#19]

**Comment by treyp** [comment]
Sorry, looks like that was me, although I don't see exactly where yet. Looks like you're working on a fix?

**Comment by teleject** [comment]
Tinkering, more than fixing, it seems. Chrome seems to be acting up on initial page view. But between options of volume and height, it respects it. Safari is doing fine.

**Comment by treyp** [comment]
merge that in and it should fix it :smiley:

**Comment by treyp** [comment]
that last commit might merge smoother. i got into a bit of git madness.
