### ISSUE TITLE
lake is measured in ft about sea level so empty is not 0 ft.

### ISSUE THREAD

**Issue by adhamhf** [sophshep/isthelakefullyet#22]
hi, nice app!  I'm being nit picky here...  The feet graph shouldn't start a 0, because that's 0 feet above sea level.  The historic low of Lake Travis is around 614 feet above sea level.  I think the bottom is actually 600 feet or so.  If you make the feet graph start a the bottom above sea level the the feet graph and volume graph will be on much closer scales.

**Comment by treyp** [comment]
I'm gonna take this by simply adjusting the notches on the left. Should be done pretty quickly.

**Comment by teleject** [comment]
Researching the "real" bottom of Lake Travis. Would like to know it before we apply this as it has the potential to make people more confused than help, esp. if we get the information wrong.

**Comment by erinknight242** [comment]
Honestly anything is closer than 681; it seems more misleading to represent
the lake as 681 ft deep.

**Comment by adhamhf** [comment]
You will never find a real "bottom" because the lake is higher above sea level at the top than it is at the dam.  The dam is 281 ft high, so you could make a guess based on that.  Or you could use the % full based on volume and estimate based on that.
